// Generated by nanobind reflection emit backend -- do not edit.
#include "binding_includes.h"

#include <nanobind/nanobind.h>
#include <nanobind/nb_paren_init.h>
#include <nanobind/trampoline.h>
#include <nanobind/stl/string.h>
#include <ostream>
#include <sstream>
#include <utility>
#include <nanobind/stl/string.h>

namespace nb = nanobind;

namespace nbgen {

template <long double, class = void> struct value_probe;

// Forward declarations (a derived class's bind function calls
// its base's regardless of definition order).
template <class Self = ::date::year> static void nbgen_bind___date__year(nb::module_ &m);
template <class Self = ::date::month> static void nbgen_bind___date__month(nb::module_ &m);
template <class Self = ::date::day> static void nbgen_bind___date__day(nb::module_ &m);
template <class Self = ::date::weekday> static void nbgen_bind___date__weekday(nb::module_ &m);
template <class Self = ::date::year_month> static void nbgen_bind___date__year_month(nb::module_ &m);
template <class Self = ::date::month_day> static void nbgen_bind___date__month_day(nb::module_ &m);
template <class Self = ::date::year_month_day> static void nbgen_bind___date__year_month_day(nb::module_ &m);

template <class Self>
static void nbgen_bind___date__year(nb::module_ &m) {
    if (nb::type<::date::year>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "year") ? "date_year" : "year";
    auto cls = nb::class_<::date::year>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<int>(), nb::arg("y"));
    cls.def(::nanobind::detail::reflect_init<const ::date::year &>());
    cls.def("__iadd__", [](::date::year &self, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year & { return self.operator+=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__isub__", [](::date::year &self, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year & { return self.operator-=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__neg__", [](const ::date::year &self) -> ::date::year { return self.operator-(); }, nb::is_operator());
    cls.def("__pos__", [](const ::date::year &self) -> ::date::year { return self.operator+(); }, nb::is_operator());
    cls.def("is_leap", [](const ::date::year &self) -> bool { return self.is_leap(); });
    cls.def("__int__", [](::date::year &self) -> long long { return (long long) self.operator int(); });
    cls.def("ok", [](const ::date::year &self) -> bool { return self.ok(); });
    cls.def_static("min", []() -> ::date::year { return ::date::year::min(); });
    cls.def_static("max", []() -> ::date::year { return ::date::year::max(); });
    cls.def("__truediv__", [](const ::date::year & a0, const ::date::month & a1) -> ::date::year_month { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year & a0, int a1) -> ::date::year_month { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year & a0, const ::date::month_day & a1) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::year & a1, const ::date::month_day & a0) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year & a0, const ::date::month_day_last & a1) -> ::date::year_month_day_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::year & a1, const ::date::month_day_last & a0) -> ::date::year_month_day_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year & a0, const ::date::month_weekday & a1) -> ::date::year_month_weekday { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::year & a1, const ::date::month_weekday & a0) -> ::date::year_month_weekday { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year & a0, const ::date::month_weekday_last & a1) -> ::date::year_month_weekday_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::year & a1, const ::date::month_weekday_last & a0) -> ::date::year_month_weekday_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__eq__", [](const ::date::year & a0, const ::date::year & a1) -> bool { return ::date::operator==(a0, a1); }, nb::is_operator());
    cls.def("__ne__", [](const ::date::year & a0, const ::date::year & a1) -> bool { return ::date::operator!=(a0, a1); }, nb::is_operator());
    cls.def("__lt__", [](const ::date::year & a0, const ::date::year & a1) -> bool { return ::date::operator<(a0, a1); }, nb::is_operator());
    cls.def("__gt__", [](const ::date::year & a0, const ::date::year & a1) -> bool { return ::date::operator>(a0, a1); }, nb::is_operator());
    cls.def("__le__", [](const ::date::year & a0, const ::date::year & a1) -> bool { return ::date::operator<=(a0, a1); }, nb::is_operator());
    cls.def("__ge__", [](const ::date::year & a0, const ::date::year & a1) -> bool { return ::date::operator>=(a0, a1); }, nb::is_operator());
    cls.def("__add__", [](const ::date::year & a0, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a1) -> ::date::year { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__radd__", [](const ::date::year & a1, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::year & a0, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a1) -> ::date::year { return ::date::operator-(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::year & a0, const ::date::year & a1) -> ::std::chrono::duration<int, ::std::ratio<31556952, 1>> { return ::date::operator-(a0, a1); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___date__month(nb::module_ &m) {
    if (nb::type<::date::month>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "month") ? "date_month" : "month";
    auto cls = nb::class_<::date::month>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<unsigned int>(), nb::arg("m"));
    cls.def(::nanobind::detail::reflect_init<const ::date::month &>());
    cls.def("__iadd__", [](::date::month &self, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a0) -> ::date::month & { return self.operator+=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__isub__", [](::date::month &self, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a0) -> ::date::month & { return self.operator-=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__int__", [](::date::month &self) -> long long { return (long long) self.operator unsigned int(); });
    cls.def("ok", [](const ::date::month &self) -> bool { return self.ok(); });
    cls.def("__rtruediv__", [](const ::date::month & a1, const ::date::year & a0) -> ::date::year_month { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::month & a1, const ::date::day & a0) -> ::date::month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::month & a0, const ::date::day & a1) -> ::date::month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::month & a0, int a1) -> ::date::month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::month & a0, ::date::last_spec a1) -> ::date::month_day_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::month & a1, ::date::last_spec a0) -> ::date::month_day_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::month & a0, const ::date::weekday_indexed & a1) -> ::date::month_weekday { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::month & a1, const ::date::weekday_indexed & a0) -> ::date::month_weekday { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::month & a0, const ::date::weekday_last & a1) -> ::date::month_weekday_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::month & a1, const ::date::weekday_last & a0) -> ::date::month_weekday_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__eq__", [](const ::date::month & a0, const ::date::month & a1) -> bool { return ::date::operator==(a0, a1); }, nb::is_operator());
    cls.def("__ne__", [](const ::date::month & a0, const ::date::month & a1) -> bool { return ::date::operator!=(a0, a1); }, nb::is_operator());
    cls.def("__lt__", [](const ::date::month & a0, const ::date::month & a1) -> bool { return ::date::operator<(a0, a1); }, nb::is_operator());
    cls.def("__gt__", [](const ::date::month & a0, const ::date::month & a1) -> bool { return ::date::operator>(a0, a1); }, nb::is_operator());
    cls.def("__le__", [](const ::date::month & a0, const ::date::month & a1) -> bool { return ::date::operator<=(a0, a1); }, nb::is_operator());
    cls.def("__ge__", [](const ::date::month & a0, const ::date::month & a1) -> bool { return ::date::operator>=(a0, a1); }, nb::is_operator());
    cls.def("__add__", [](const ::date::month & a0, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a1) -> ::date::month { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__radd__", [](const ::date::month & a1, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a0) -> ::date::month { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::month & a0, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a1) -> ::date::month { return ::date::operator-(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::month & a0, const ::date::month & a1) -> ::std::chrono::duration<int, ::std::ratio<2629746, 1>> { return ::date::operator-(a0, a1); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___date__day(nb::module_ &m) {
    if (nb::type<::date::day>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "day") ? "date_day" : "day";
    auto cls = nb::class_<::date::day>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<unsigned int>(), nb::arg("d"));
    cls.def(::nanobind::detail::reflect_init<const ::date::day &>());
    cls.def("__iadd__", [](::date::day &self, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a0) -> ::date::day & { return self.operator+=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<86400, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__isub__", [](::date::day &self, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a0) -> ::date::day & { return self.operator-=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<86400, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__int__", [](::date::day &self) -> long long { return (long long) self.operator unsigned int(); });
    cls.def("ok", [](const ::date::day &self) -> bool { return self.ok(); });
    cls.def("__truediv__", [](const ::date::day & a0, const ::date::month & a1) -> ::date::month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::day & a0, int a1) -> ::date::month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::day & a1, const ::date::month & a0) -> ::date::month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::day & a1, int a0) -> ::date::month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::day & a1, const ::date::year_month & a0) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__eq__", [](const ::date::day & a0, const ::date::day & a1) -> bool { return ::date::operator==(a0, a1); }, nb::is_operator());
    cls.def("__ne__", [](const ::date::day & a0, const ::date::day & a1) -> bool { return ::date::operator!=(a0, a1); }, nb::is_operator());
    cls.def("__lt__", [](const ::date::day & a0, const ::date::day & a1) -> bool { return ::date::operator<(a0, a1); }, nb::is_operator());
    cls.def("__gt__", [](const ::date::day & a0, const ::date::day & a1) -> bool { return ::date::operator>(a0, a1); }, nb::is_operator());
    cls.def("__le__", [](const ::date::day & a0, const ::date::day & a1) -> bool { return ::date::operator<=(a0, a1); }, nb::is_operator());
    cls.def("__ge__", [](const ::date::day & a0, const ::date::day & a1) -> bool { return ::date::operator>=(a0, a1); }, nb::is_operator());
    cls.def("__add__", [](const ::date::day & a0, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a1) -> ::date::day { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__radd__", [](const ::date::day & a1, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a0) -> ::date::day { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::day & a0, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a1) -> ::date::day { return ::date::operator-(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::day & a0, const ::date::day & a1) -> ::std::chrono::duration<int, ::std::ratio<86400, 1>> { return ::date::operator-(a0, a1); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___date__weekday(nb::module_ &m) {
    if (nb::type<::date::weekday>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "weekday") ? "date_weekday" : "weekday";
    auto cls = nb::class_<::date::weekday>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<unsigned int>(), nb::arg("wd"));
    cls.def(::nanobind::detail::reflect_init<const ::std::chrono::time_point<::std::chrono::system_clock, ::std::chrono::duration<int, ::std::ratio<86400, 1>>> &>(), nb::arg("dp"));
    cls.def(::nanobind::detail::reflect_init<const ::std::chrono::time_point<::date::local_t, ::std::chrono::duration<int, ::std::ratio<86400, 1>>> &>(), nb::arg("dp"));
    cls.def(::nanobind::detail::reflect_init<const ::date::weekday &>());
    cls.def("__iadd__", [](::date::weekday &self, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a0) -> ::date::weekday & { return self.operator+=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<86400, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__isub__", [](::date::weekday &self, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a0) -> ::date::weekday & { return self.operator-=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<86400, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("ok", [](const ::date::weekday &self) -> bool { return self.ok(); });
    cls.def("c_encoding", [](const ::date::weekday &self) -> unsigned int { return self.c_encoding(); });
    cls.def("iso_encoding", [](const ::date::weekday &self) -> unsigned int { return self.iso_encoding(); });
    cls.def("__getitem__", [](const ::date::weekday &self, unsigned int a0) -> ::date::weekday_indexed { return self.operator[](::std::forward<unsigned int>(a0)); }, nb::is_operator());
    cls.def("__getitem__", [](const ::date::weekday &self, ::date::last_spec a0) -> ::date::weekday_last { return self.operator[](::std::forward<::date::last_spec>(a0)); }, nb::is_operator());
    cls.def("__eq__", [](const ::date::weekday & a0, const ::date::weekday & a1) -> bool { return ::date::operator==(a0, a1); }, nb::is_operator());
    cls.def("__ne__", [](const ::date::weekday & a0, const ::date::weekday & a1) -> bool { return ::date::operator!=(a0, a1); }, nb::is_operator());
    cls.def("__add__", [](const ::date::weekday & a0, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a1) -> ::date::weekday { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__radd__", [](const ::date::weekday & a1, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a0) -> ::date::weekday { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::weekday & a0, const ::std::chrono::duration<int, ::std::ratio<86400, 1>> & a1) -> ::date::weekday { return ::date::operator-(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::weekday & a0, const ::date::weekday & a1) -> ::std::chrono::duration<int, ::std::ratio<86400, 1>> { return ::date::operator-(a0, a1); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___date__year_month(nb::module_ &m) {
    if (nb::type<::date::year_month>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "year_month") ? "date_year_month" : "year_month";
    auto cls = nb::class_<::date::year_month>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::date::year &, const ::date::month &>(), nb::arg("y"), nb::arg("m"));
    cls.def(::nanobind::detail::reflect_init<const ::date::year_month &>());
    cls.def("year", [](const ::date::year_month &self) -> ::date::year { return self.year(); });
    cls.def("month", [](const ::date::year_month &self) -> ::date::month { return self.month(); });
    cls.def("__iadd__", [](::date::year_month &self, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a0) -> ::date::year_month & { return self.operator+=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__isub__", [](::date::year_month &self, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a0) -> ::date::year_month & { return self.operator-=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__iadd__", [](::date::year_month &self, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year_month & { return self.operator+=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__isub__", [](::date::year_month &self, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year_month & { return self.operator-=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("ok", [](const ::date::year_month &self) -> bool { return self.ok(); });
    cls.def("__truediv__", [](const ::date::year_month & a0, const ::date::day & a1) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year_month & a0, int a1) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year_month & a0, ::date::last_spec a1) -> ::date::year_month_day_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year_month & a0, const ::date::weekday_indexed & a1) -> ::date::year_month_weekday { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::year_month & a0, const ::date::weekday_last & a1) -> ::date::year_month_weekday_last { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__eq__", [](const ::date::year_month & a0, const ::date::year_month & a1) -> bool { return ::date::operator==(a0, a1); }, nb::is_operator());
    cls.def("__ne__", [](const ::date::year_month & a0, const ::date::year_month & a1) -> bool { return ::date::operator!=(a0, a1); }, nb::is_operator());
    cls.def("__lt__", [](const ::date::year_month & a0, const ::date::year_month & a1) -> bool { return ::date::operator<(a0, a1); }, nb::is_operator());
    cls.def("__gt__", [](const ::date::year_month & a0, const ::date::year_month & a1) -> bool { return ::date::operator>(a0, a1); }, nb::is_operator());
    cls.def("__le__", [](const ::date::year_month & a0, const ::date::year_month & a1) -> bool { return ::date::operator<=(a0, a1); }, nb::is_operator());
    cls.def("__ge__", [](const ::date::year_month & a0, const ::date::year_month & a1) -> bool { return ::date::operator>=(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::year_month & a0, const ::date::year_month & a1) -> ::std::chrono::duration<int, ::std::ratio<2629746, 1>> { return ::date::operator-(a0, a1); }, nb::is_operator());
    cls.def("__add__", [](const ::date::year_month & a0, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a1) -> ::date::year_month { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__radd__", [](const ::date::year_month & a1, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year_month { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::year_month & a0, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a1) -> ::date::year_month { return ::date::operator-(a0, a1); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___date__month_day(nb::module_ &m) {
    if (nb::type<::date::month_day>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "month_day") ? "date_month_day" : "month_day";
    auto cls = nb::class_<::date::month_day>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::date::month &, const ::date::day &>(), nb::arg("m"), nb::arg("d"));
    cls.def(::nanobind::detail::reflect_init<const ::date::month_day &>());
    cls.def("month", [](const ::date::month_day &self) -> ::date::month { return self.month(); });
    cls.def("day", [](const ::date::month_day &self) -> ::date::day { return self.day(); });
    cls.def("ok", [](const ::date::month_day &self) -> bool { return self.ok(); });
    cls.def("__rtruediv__", [](const ::date::month_day & a1, const ::date::year & a0) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__rtruediv__", [](const ::date::month_day & a1, int a0) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::month_day & a0, const ::date::year & a1) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__truediv__", [](const ::date::month_day & a0, int a1) -> ::date::year_month_day { return ::date::operator/(a0, a1); }, nb::is_operator());
    cls.def("__eq__", [](const ::date::month_day & a0, const ::date::month_day & a1) -> bool { return ::date::operator==(a0, a1); }, nb::is_operator());
    cls.def("__ne__", [](const ::date::month_day & a0, const ::date::month_day & a1) -> bool { return ::date::operator!=(a0, a1); }, nb::is_operator());
    cls.def("__lt__", [](const ::date::month_day & a0, const ::date::month_day & a1) -> bool { return ::date::operator<(a0, a1); }, nb::is_operator());
    cls.def("__gt__", [](const ::date::month_day & a0, const ::date::month_day & a1) -> bool { return ::date::operator>(a0, a1); }, nb::is_operator());
    cls.def("__le__", [](const ::date::month_day & a0, const ::date::month_day & a1) -> bool { return ::date::operator<=(a0, a1); }, nb::is_operator());
    cls.def("__ge__", [](const ::date::month_day & a0, const ::date::month_day & a1) -> bool { return ::date::operator>=(a0, a1); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___date__year_month_day(nb::module_ &m) {
    if (nb::type<::date::year_month_day>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "year_month_day") ? "date_year_month_day" : "year_month_day";
    auto cls = nb::class_<::date::year_month_day>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::date::year &, const ::date::month &, const ::date::day &>(), nb::arg("y"), nb::arg("m"), nb::arg("d"));
    cls.def(::nanobind::detail::reflect_init<const ::date::year_month_day_last &>(), nb::arg("ymdl"));
    cls.def(::nanobind::detail::reflect_init<::std::chrono::time_point<::std::chrono::system_clock, ::std::chrono::duration<int, ::std::ratio<86400, 1>>>>(), nb::arg("dp"));
    cls.def(::nanobind::detail::reflect_init<::std::chrono::time_point<::date::local_t, ::std::chrono::duration<int, ::std::ratio<86400, 1>>>>(), nb::arg("dp"));
    cls.def(::nanobind::detail::reflect_init<const ::date::year_month_day &>());
    cls.def("__iadd__", [](::date::year_month_day &self, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a0) -> ::date::year_month_day & { return self.operator+=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__isub__", [](::date::year_month_day &self, const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> & a0) -> ::date::year_month_day & { return self.operator-=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<2629746, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__iadd__", [](::date::year_month_day &self, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year_month_day & { return self.operator+=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("__isub__", [](::date::year_month_day &self, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year_month_day & { return self.operator-=(::std::forward<const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> &>(a0)); }, nb::is_operator(), nb::rv_policy::reference);
    cls.def("year", [](const ::date::year_month_day &self) -> ::date::year { return self.year(); });
    cls.def("month", [](const ::date::year_month_day &self) -> ::date::month { return self.month(); });
    cls.def("day", [](const ::date::year_month_day &self) -> ::date::day { return self.day(); });
    cls.def("ok", [](const ::date::year_month_day &self) -> bool { return self.ok(); });
    cls.def("__eq__", [](const ::date::year_month_day & a0, const ::date::year_month_day & a1) -> bool { return ::date::operator==(a0, a1); }, nb::is_operator());
    cls.def("__ne__", [](const ::date::year_month_day & a0, const ::date::year_month_day & a1) -> bool { return ::date::operator!=(a0, a1); }, nb::is_operator());
    cls.def("__lt__", [](const ::date::year_month_day & a0, const ::date::year_month_day & a1) -> bool { return ::date::operator<(a0, a1); }, nb::is_operator());
    cls.def("__gt__", [](const ::date::year_month_day & a0, const ::date::year_month_day & a1) -> bool { return ::date::operator>(a0, a1); }, nb::is_operator());
    cls.def("__le__", [](const ::date::year_month_day & a0, const ::date::year_month_day & a1) -> bool { return ::date::operator<=(a0, a1); }, nb::is_operator());
    cls.def("__ge__", [](const ::date::year_month_day & a0, const ::date::year_month_day & a1) -> bool { return ::date::operator>=(a0, a1); }, nb::is_operator());
    cls.def("__add__", [](const ::date::year_month_day & a0, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a1) -> ::date::year_month_day { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__radd__", [](const ::date::year_month_day & a1, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a0) -> ::date::year_month_day { return ::date::operator+(a0, a1); }, nb::is_operator());
    cls.def("__sub__", [](const ::date::year_month_day & a0, const ::std::chrono::duration<int, ::std::ratio<31556952, 1>> & a1) -> ::date::year_month_day { return ::date::operator-(a0, a1); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

} // namespace nbgen

NB_MODULE(date_ext, m) {
    nbgen::nbgen_bind___date__year(m);
    nbgen::nbgen_bind___date__month(m);
    nbgen::nbgen_bind___date__day(m);
    nbgen::nbgen_bind___date__weekday(m);
    nbgen::nbgen_bind___date__year_month(m);
    nbgen::nbgen_bind___date__month_day(m);
    nbgen::nbgen_bind___date__year_month_day(m);
    m.def("ymd_to_serial", [](const ::date::year_month_day & a0) -> long { return ::datefix::ymd_to_serial(::std::forward<const ::date::year_month_day &>(a0)); }, nb::arg("ymd"));
    m.def("serial_to_ymd", [](long a0) -> ::datefix::year_month_day { return ::datefix::serial_to_ymd(::std::forward<long>(a0)); }, nb::arg("serial"));
    m.def("weekday_of", [](const ::date::year_month_day & a0) -> ::datefix::weekday { return ::datefix::weekday_of(::std::forward<const ::date::year_month_day &>(a0)); }, nb::arg("ymd"));
    m.def("format_ymd", [](const ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> & a0, const ::date::year_month_day & a1) -> ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> { return ::datefix::format_ymd(::std::forward<const ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> &>(a0), ::std::forward<const ::date::year_month_day &>(a1)); }, nb::arg("fmt"), nb::arg("ymd"));
    m.def("format_weekday", [](const ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> & a0, const ::date::weekday & a1) -> ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> { return ::datefix::format_weekday(::std::forward<const ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> &>(a0), ::std::forward<const ::date::weekday &>(a1)); }, nb::arg("fmt"), nb::arg("wd"));
}
