// Generated by nanobind reflection emit backend -- do not edit.
#define TINYOBJLOADER_IMPLEMENTATION
#include "binding_includes.h"

#include <nanobind/nanobind.h>
#include <nanobind/nb_paren_init.h>
#include <nanobind/trampoline.h>
#include <nanobind/stl/string.h>
#include <ostream>
#include <sstream>
#include <utility>
#include <nanobind/stl/vector.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/vector.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/map.h>
#include <nanobind/stl/string.h>
#include <nanobind/stl/vector.h>

namespace nb = nanobind;

namespace nbgen {

template <long double, class = void> struct value_probe;

// Forward declarations (a derived class's bind function calls
// its base's regardless of definition order).
template <class Self = ::tinyobj::index_t> static void nbgen_bind___tinyobj__index_t(nb::module_ &m);
template <class Self = ::tinyobj::mesh_t> static void nbgen_bind___tinyobj__mesh_t(nb::module_ &m);
template <class Self = ::tinyobj::shape_t> static void nbgen_bind___tinyobj__shape_t(nb::module_ &m);
template <class Self = ::tinyobj::attrib_t> static void nbgen_bind___tinyobj__attrib_t(nb::module_ &m);
template <class Self = ::tinyobj::material_t> static void nbgen_bind___tinyobj__material_t(nb::module_ &m);
template <class Self = ::objtest::LoadResult> static void nbgen_bind___objtest__LoadResult(nb::module_ &m);

template <class Self>
static void nbgen_bind___tinyobj__index_t(nb::module_ &m) {
    if (nb::type<::tinyobj::index_t>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "index_t") ? "tinyobj_index_t" : "index_t";
    auto cls = nb::class_<::tinyobj::index_t>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::tinyobj::index_t &>());
    cls.def_rw("vertex_index", &::tinyobj::index_t::vertex_index);
    cls.def_rw("normal_index", &::tinyobj::index_t::normal_index);
    cls.def_rw("texcoord_index", &::tinyobj::index_t::texcoord_index);
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___tinyobj__mesh_t(nb::module_ &m) {
    if (nb::type<::tinyobj::mesh_t>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "mesh_t") ? "tinyobj_mesh_t" : "mesh_t";
    auto cls = nb::class_<::tinyobj::mesh_t>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::tinyobj::mesh_t &>());
    cls.def_rw("indices", &::tinyobj::mesh_t::indices);
    cls.def_rw("num_face_vertices", &::tinyobj::mesh_t::num_face_vertices);
    cls.def_rw("material_ids", &::tinyobj::mesh_t::material_ids);
    cls.def_rw("smoothing_group_ids", &::tinyobj::mesh_t::smoothing_group_ids);
    cls.def_rw("tags", &::tinyobj::mesh_t::tags);
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___tinyobj__shape_t(nb::module_ &m) {
    if (nb::type<::tinyobj::shape_t>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "shape_t") ? "tinyobj_shape_t" : "shape_t";
    auto cls = nb::class_<::tinyobj::shape_t>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::tinyobj::shape_t &>());
    cls.def_rw("name", &::tinyobj::shape_t::name);
    cls.def_rw("mesh", &::tinyobj::shape_t::mesh);
    cls.def_rw("path", &::tinyobj::shape_t::path);
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___tinyobj__attrib_t(nb::module_ &m) {
    if (nb::type<::tinyobj::attrib_t>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "attrib_t") ? "tinyobj_attrib_t" : "attrib_t";
    auto cls = nb::class_<::tinyobj::attrib_t>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::tinyobj::attrib_t &>());
    cls.def_rw("vertices", &::tinyobj::attrib_t::vertices);
    cls.def_rw("normals", &::tinyobj::attrib_t::normals);
    cls.def_rw("texcoords", &::tinyobj::attrib_t::texcoords);
    cls.def_rw("colors", &::tinyobj::attrib_t::colors);
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___tinyobj__material_t(nb::module_ &m) {
    if (nb::type<::tinyobj::material_t>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "material_t") ? "tinyobj_material_t" : "material_t";
    auto cls = nb::class_<::tinyobj::material_t>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::tinyobj::material_t &>());
    cls.def_rw("name", &::tinyobj::material_t::name);
    cls.def_rw("shininess", &::tinyobj::material_t::shininess);
    cls.def_rw("ior", &::tinyobj::material_t::ior);
    cls.def_rw("dissolve", &::tinyobj::material_t::dissolve);
    cls.def_rw("illum", &::tinyobj::material_t::illum);
    cls.def_rw("dummy", &::tinyobj::material_t::dummy);
    cls.def_rw("ambient_texname", &::tinyobj::material_t::ambient_texname);
    cls.def_rw("diffuse_texname", &::tinyobj::material_t::diffuse_texname);
    cls.def_rw("specular_texname", &::tinyobj::material_t::specular_texname);
    cls.def_rw("specular_highlight_texname", &::tinyobj::material_t::specular_highlight_texname);
    cls.def_rw("bump_texname", &::tinyobj::material_t::bump_texname);
    cls.def_rw("displacement_texname", &::tinyobj::material_t::displacement_texname);
    cls.def_rw("alpha_texname", &::tinyobj::material_t::alpha_texname);
    cls.def_rw("reflection_texname", &::tinyobj::material_t::reflection_texname);
    cls.def_rw("ambient_texopt", &::tinyobj::material_t::ambient_texopt);
    cls.def_rw("diffuse_texopt", &::tinyobj::material_t::diffuse_texopt);
    cls.def_rw("specular_texopt", &::tinyobj::material_t::specular_texopt);
    cls.def_rw("specular_highlight_texopt", &::tinyobj::material_t::specular_highlight_texopt);
    cls.def_rw("bump_texopt", &::tinyobj::material_t::bump_texopt);
    cls.def_rw("displacement_texopt", &::tinyobj::material_t::displacement_texopt);
    cls.def_rw("alpha_texopt", &::tinyobj::material_t::alpha_texopt);
    cls.def_rw("reflection_texopt", &::tinyobj::material_t::reflection_texopt);
    cls.def_rw("roughness", &::tinyobj::material_t::roughness);
    cls.def_rw("metallic", &::tinyobj::material_t::metallic);
    cls.def_rw("sheen", &::tinyobj::material_t::sheen);
    cls.def_rw("clearcoat_thickness", &::tinyobj::material_t::clearcoat_thickness);
    cls.def_rw("clearcoat_roughness", &::tinyobj::material_t::clearcoat_roughness);
    cls.def_rw("anisotropy", &::tinyobj::material_t::anisotropy);
    cls.def_rw("anisotropy_rotation", &::tinyobj::material_t::anisotropy_rotation);
    cls.def_rw("pad0", &::tinyobj::material_t::pad0);
    cls.def_rw("roughness_texname", &::tinyobj::material_t::roughness_texname);
    cls.def_rw("metallic_texname", &::tinyobj::material_t::metallic_texname);
    cls.def_rw("sheen_texname", &::tinyobj::material_t::sheen_texname);
    cls.def_rw("emissive_texname", &::tinyobj::material_t::emissive_texname);
    cls.def_rw("normal_texname", &::tinyobj::material_t::normal_texname);
    cls.def_rw("roughness_texopt", &::tinyobj::material_t::roughness_texopt);
    cls.def_rw("metallic_texopt", &::tinyobj::material_t::metallic_texopt);
    cls.def_rw("sheen_texopt", &::tinyobj::material_t::sheen_texopt);
    cls.def_rw("emissive_texopt", &::tinyobj::material_t::emissive_texopt);
    cls.def_rw("normal_texopt", &::tinyobj::material_t::normal_texopt);
    cls.def_rw("pad2", &::tinyobj::material_t::pad2);
    cls.def_rw("unknown_parameter", &::tinyobj::material_t::unknown_parameter);
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___objtest__LoadResult(nb::module_ &m) {
    if (nb::type<::objtest::LoadResult>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "LoadResult") ? "objtest_LoadResult" : "LoadResult";
    auto cls = nb::class_<::objtest::LoadResult>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const ::objtest::LoadResult &>());
    cls.def_rw("success", &::objtest::LoadResult::success);
    cls.def_rw("warn", &::objtest::LoadResult::warn);
    cls.def_rw("err", &::objtest::LoadResult::err);
    cls.def_rw("attrib", &::objtest::LoadResult::attrib);
    cls.def_rw("shapes", &::objtest::LoadResult::shapes);
    cls.def_rw("materials", &::objtest::LoadResult::materials);
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

} // namespace nbgen

NB_MODULE(tinyobjloader_ext, m) {
    nbgen::nbgen_bind___tinyobj__index_t(m);
    nbgen::nbgen_bind___tinyobj__mesh_t(m);
    nbgen::nbgen_bind___tinyobj__shape_t(m);
    nbgen::nbgen_bind___tinyobj__attrib_t(m);
    nbgen::nbgen_bind___tinyobj__material_t(m);
    nbgen::nbgen_bind___objtest__LoadResult(m);
    m.def("parse_obj", [](const ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> & a0, bool a1) -> ::objtest::LoadResult { return ::objtest::parse_obj(::std::forward<const ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> &>(a0), ::std::forward<bool>(a1)); }, nb::arg("obj_text"), nb::arg("triangulate"));
}
