// Generated by nanobind reflection emit backend -- do not edit.
#include "binding_includes.h"

#include <nanobind/nanobind.h>
#include <nanobind/nb_paren_init.h>
#include <nanobind/trampoline.h>
#include <nanobind/stl/string.h>
#include <ostream>
#include <sstream>
#include <utility>
#include <nanobind/stl/vector.h>

namespace nb = nanobind;

namespace nbgen {

template <long double, class = void> struct value_probe;

// Forward declarations (a derived class's bind function calls
// its base's regardless of definition order).
template <class Self = ::tree::Node> static void nbgen_bind___tree__Node(nb::module_ &m);

template <class Self>
static void nbgen_bind___tree__Node(nb::module_ &m) {
    if (nb::type<::tree::Node>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "Node") ? "tree_Node" : "Node";
    auto cls = nb::class_<::tree::Node>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<int>(), nb::arg("v"));
    cls.def(::nanobind::detail::reflect_init<const ::tree::Node &>());
    cls.def_rw("value", &::tree::Node::value);
    cls.def_rw("children", &::tree::Node::children);
    cls.def("add", [](::tree::Node &self, const ::tree::Node & a0) -> void { return self.add(::std::forward<const ::tree::Node &>(a0)); }, nb::arg("n"));
    cls.def("count", [](const ::tree::Node &self) -> long { return self.count(); });
    cls.def("total", [](const ::tree::Node &self) -> int { return self.total(); });
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

} // namespace nbgen

NB_MODULE(tree_ext, m) {
    nbgen::nbgen_bind___tree__Node(m);
}
