// Generated by nanobind reflection emit backend -- do not edit.
#include "binding_includes.h"

#include <nanobind/nanobind.h>
#include <nanobind/nb_paren_init.h>
#include <nanobind/trampoline.h>
#include <nanobind/stl/string.h>
#include <ostream>
#include <sstream>
#include <utility>

namespace nb = nanobind;

namespace nbgen {

template <long double, class = void> struct value_probe;

// Forward declarations (a derived class's bind function calls
// its base's regardless of definition order).
template <class Self = ::podfix::Point> static void nbgen_bind___podfix__Point(nb::module_ &m);
template <class Self = ::podfix::Axis> static void nbgen_bind___podfix__Axis(nb::module_ &m);

template <class Self>
static void nbgen_bind___podfix__Point(nb::module_ &m) {
    if (nb::type<::podfix::Point>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "Point") ? "podfix_Point" : "Point";
    auto cls = nb::class_<::podfix::Point>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<double, double>(), nb::arg("x_"), nb::arg("y_"));
    cls.def(::nanobind::detail::reflect_init<const ::podfix::Point &>());
    cls.def_rw("x", &::podfix::Point::x);
    cls.def_rw("y", &::podfix::Point::y);
    cls.def("norm2", [](const ::podfix::Point &self) -> double { return self.norm2(); });
    cls.def("scale", [](::podfix::Point &self, double a0) -> void { return self.scale(::std::forward<double>(a0)); }, nb::arg("f"));
    cls.def_static("origin", []() -> ::podfix::Point { return ::podfix::Point::origin(); });
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___podfix__Axis(nb::module_ &m) {
    if (nb::type<::podfix::Axis>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "Axis") ? "podfix_Axis" : "Axis";
    auto e = nb::enum_<::podfix::Axis>(m, py_name);
    e.value("X", ::podfix::Axis::X);
    e.value("Y", ::podfix::Axis::Y);
    e.value("Z", ::podfix::Axis::Z);
}

} // namespace nbgen

NB_MODULE(pod_fixture_ext, m) {
    nbgen::nbgen_bind___podfix__Point(m);
    nbgen::nbgen_bind___podfix__Axis(m);
    m.def("add", [](const ::podfix::Point & a0, const ::podfix::Point & a1) -> ::podfix::Point { return ::podfix::add(::std::forward<const ::podfix::Point &>(a0), ::std::forward<const ::podfix::Point &>(a1)); }, nb::arg("a"), nb::arg("b"));
    m.def("dot", [](const ::podfix::Point & a0, const ::podfix::Point & a1) -> double { return ::podfix::dot(::std::forward<const ::podfix::Point &>(a0), ::std::forward<const ::podfix::Point &>(a1)); }, nb::arg("a"), nb::arg("b"));
}
