// Generated by nanobind reflection emit backend -- do not edit.
#include "binding_includes.h"

#include <nanobind/nanobind.h>
#include <nanobind/nb_paren_init.h>
#include <nanobind/trampoline.h>
#include <nanobind/stl/string.h>
#include <ostream>
#include <sstream>
#include <utility>

namespace nb = nanobind;

namespace nbgen {

template <long double, class = void> struct value_probe;

// Forward declarations (a derived class's bind function calls
// its base's regardless of definition order).
template <class Self = ::glm::vec<3, float, ::glm::qualifier::packed_highp>> static void nbgen_bind___glm__vec_L3_Cfloat_C__glm__qualifier__packed_highp_R(nb::module_ &m);
template <class Self = ::glm::vec<4, float, ::glm::qualifier::packed_highp>> static void nbgen_bind___glm__vec_L4_Cfloat_C__glm__qualifier__packed_highp_R(nb::module_ &m);

template <class Self>
static void nbgen_bind___glm__vec_L3_Cfloat_C__glm__qualifier__packed_highp_R(nb::module_ &m) {
    if (nb::type<::glm::vec<3, float, ::glm::qualifier::packed_highp>>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "vec3FloatUnsupportedreflection") ? "glm_vec3FloatUnsupportedreflection" : "vec3FloatUnsupportedreflection";
    auto cls = nb::class_<::glm::vec<3, float, ::glm::qualifier::packed_highp>>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<float>(), nb::arg("scalar"));
    cls.def(::nanobind::detail::reflect_init<float, float, float>(), nb::arg("a"), nb::arg("b"), nb::arg("c"));
    cls.def(::nanobind::detail::reflect_init<const ::glm::vec<3, float, ::glm::qualifier::packed_highp> &>());
    cls.def_static("length", []() -> int { return ::glm::vec<3, float, ::glm::qualifier::packed_highp>::length(); });
    cls.def("__getitem__", [](::glm::vec<3, float, ::glm::qualifier::packed_highp> &self, int a0) -> float & { return self.operator[](::std::forward<int>(a0)); }, nb::is_operator());
    cls.def("__getitem__", [](const ::glm::vec<3, float, ::glm::qualifier::packed_highp> &self, int a0) -> const float & { return self.operator[](::std::forward<int>(a0)); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___glm__vec_L4_Cfloat_C__glm__qualifier__packed_highp_R(nb::module_ &m) {
    if (nb::type<::glm::vec<4, float, ::glm::qualifier::packed_highp>>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "vec4FloatUnsupportedreflection") ? "glm_vec4FloatUnsupportedreflection" : "vec4FloatUnsupportedreflection";
    auto cls = nb::class_<::glm::vec<4, float, ::glm::qualifier::packed_highp>>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<float>(), nb::arg("scalar"));
    cls.def(::nanobind::detail::reflect_init<float, float, float, float>(), nb::arg("_x"), nb::arg("_y"), nb::arg("_z"), nb::arg("_w"));
    cls.def(::nanobind::detail::reflect_init<const ::glm::vec<4, float, ::glm::qualifier::packed_highp> &>());
    cls.def_static("length", []() -> int { return ::glm::vec<4, float, ::glm::qualifier::packed_highp>::length(); });
    cls.def("__getitem__", [](::glm::vec<4, float, ::glm::qualifier::packed_highp> &self, int a0) -> float & { return self.operator[](::std::forward<int>(a0)); }, nb::is_operator());
    cls.def("__getitem__", [](const ::glm::vec<4, float, ::glm::qualifier::packed_highp> &self, int a0) -> const float & { return self.operator[](::std::forward<int>(a0)); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

} // namespace nbgen

NB_MODULE(glm_ext, m) {
    nbgen::nbgen_bind___glm__vec_L3_Cfloat_C__glm__qualifier__packed_highp_R(m);
    nbgen::nbgen_bind___glm__vec_L4_Cfloat_C__glm__qualifier__packed_highp_R(m);
    nbgen::nbgen_bind___glm__vec_L3_Cfloat_C__glm__qualifier__packed_highp_R(m);
    nbgen::nbgen_bind___glm__vec_L4_Cfloat_C__glm__qualifier__packed_highp_R(m);
}
