// Two-stage bindings module (constexpr lane). Includes the generated
// trampoline header BEFORE reflect_, so the MB_REFLECT_TRAMPOLINE
// registrations are visible when reflect_class instantiates.
#include <mirrorbind/reflect.h>
#include <nanobind/trampoline.h>

#include "binding_args.h"
#include "trampolines.gen.h"   // generated by gen.cpp at build time

namespace nb = nanobind;
namespace mb = mirrorbind;

NB_MODULE(shapes_ext, m) {
    mb::reflect_<CORPUS_REFLECT_ARGS>(m);
}
