// Two-stage bindings module. Includes the generated trampoline header (produced at build
// time into the build dir, which is on the include path) BEFORE reflect_, so the generated
// NB_REFLECT_TRAMPOLINE registrations are visible when reflect_class instantiates.
#include <nanobind/nb_reflect.h>
#include <nanobind/trampoline.h>

#include "shapes.h"
#include "trampolines.gen.h"   // generated by gen.cpp at build time

namespace nb = nanobind;

NB_MODULE(shapes_ext, m) {
    nb::reflect_<^^shapes>(m);
}
