// Generated by nanobind reflection emit backend -- do not edit.
#include "binding_includes.h"

#include <nanobind/nanobind.h>
#include <nanobind/nb_paren_init.h>
#include <nanobind/trampoline.h>
#include <nanobind/stl/string.h>
#include <ostream>
#include <sstream>
#include <utility>
#include <nanobind/stl/string.h>

namespace nb = nanobind;

namespace nbgen {

template <long double, class = void> struct value_probe;

// Forward declarations (a derived class's bind function calls its
// base's regardless of definition order).
template <class Self = ::shapes::Shape> static void nbgen_bind___shapes__Shape(nb::module_ &m);
template <class Self = ::shapes::Circle> static void nbgen_bind___shapes__Circle(nb::module_ &m);

struct NbGenTramp___shapes__Shape : ::shapes::Shape {
    NB_TRAMPOLINE(::shapes::Shape, 2);
    double area() const override { NB_OVERRIDE_PURE(area); }
    ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> name() const override { NB_OVERRIDE(name); }
};

template <class Self>
static void nbgen_bind___shapes__Shape(nb::module_ &m) {
    if (nb::type<::shapes::Shape>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "Shape") ? "shapes_Shape" : "Shape";
    auto cls = nb::class_<::shapes::Shape, NbGenTramp___shapes__Shape>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def("area", [](const ::shapes::Shape &self) -> double { return self.area(); });
    cls.def("name", [](const ::shapes::Shape &self) -> ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> { return self.name(); });
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

struct NbGenTramp___shapes__Circle : ::shapes::Circle {
    NB_TRAMPOLINE(::shapes::Circle, 2);
    double area() const override { NB_OVERRIDE(area); }
    ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> name() const override { NB_OVERRIDE(name); }
};

template <class Self>
static void nbgen_bind___shapes__Circle(nb::module_ &m) {
    if (nb::type<::shapes::Circle>().is_valid()) return;
    nbgen_bind___shapes__Shape(m);
    const char *py_name = nb::hasattr(m, "Circle") ? "shapes_Circle" : "Circle";
    auto cls = nb::class_<::shapes::Circle, ::shapes::Shape, NbGenTramp___shapes__Circle>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<double>(), nb::arg("r_"));
    cls.def_rw("r", &::shapes::Circle::r);
    cls.def("area", [](const ::shapes::Circle &self) -> double { return self.area(); });
    cls.def("name", [](const ::shapes::Circle &self) -> ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> { return self.name(); });
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

} // namespace nbgen

NB_MODULE(shapes_ext, m) {
    nbgen::nbgen_bind___shapes__Shape(m);
    nbgen::nbgen_bind___shapes__Circle(m);
    m.def("call_area", [](const ::shapes::Shape & a0) -> double { return ::shapes::call_area(::std::forward<const ::shapes::Shape &>(a0)); }, nb::arg("s"));
    m.def("call_name", [](const ::shapes::Shape & a0) -> ::std::basic_string<char, ::std::char_traits<char>, ::std::allocator<char>> { return ::shapes::call_name(::std::forward<const ::shapes::Shape &>(a0)); }, nb::arg("s"));
}
