// Two-stage bindings for nlohmann/json (constexpr lane). The generated header
// (STL caster includes for json's signatures) is included before reflect_.
#include <mirrorbind/reflect.h>
#include <nanobind/trampoline.h>

#include "binding_args.h"
#include "trampolines.gen.h"   // generated by gen.cpp at build time

namespace nb = nanobind;
namespace mb = mirrorbind;

NB_MODULE(json_ext, m) {
    mb::reflect_<CORPUS_REFLECT_ARGS>(m);
}
