// Two-stage bindings for nlohmann/json. The generated header (STL caster includes for json's
// signatures) is included before reflect_. Subset: the json value type, its value_t enum, and the
// jsontest fixture factories/extractors.
#include <nanobind/nb_reflect.h>
#include <nanobind/trampoline.h>

#include "jsontest.h"
#include "trampolines.gen.h"   // generated by gen.cpp at build time

namespace nb = nanobind;

NB_MODULE(json_ext, m) {
    nb::reflect_<^^nlohmann::json, ^^nlohmann::detail::value_t, ^^jsontest>(m);
}
