// Two-stage bindings for nlohmann/json (constexpr lane). The generated header
// (STL caster includes for json's signatures) is included before reflect_.
#include <nanobind/nb_reflect.h>
#include <nanobind/trampoline.h>

#include "binding_args.h"
#include "trampolines.gen.h"   // generated by gen.cpp at build time

namespace nb = nanobind;

NB_MODULE(json_ext, m) {
    nb::reflect_<CORPUS_REFLECT_ARGS>(m);
}
