// Generated by nanobind reflection emit backend -- do not edit.
#include "binding_includes.h"

#include <nanobind/nanobind.h>
#include <nanobind/nb_paren_init.h>
#include <nanobind/trampoline.h>
#include <nanobind/stl/string.h>
#include <ostream>
#include <sstream>
#include <utility>

namespace nb = nanobind;

namespace nbgen {

template <long double, class = void> struct value_probe;

// Forward declarations (a derived class's bind function calls
// its base's regardless of definition order).
template <class Self = ::linalg::vec<float, 3>> static void nbgen_bind___linalg__vec_Lfloat_C3_R(nb::module_ &m);
template <class Self = ::linalg::vec<float, 2>> static void nbgen_bind___linalg__vec_Lfloat_C2_R(nb::module_ &m);

template <class Self>
static void nbgen_bind___linalg__vec_Lfloat_C3_R(nb::module_ &m) {
    if (nb::type<::linalg::vec<float, 3>>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "vecFloat3") ? "linalg_vecFloat3" : "vecFloat3";
    auto cls = nb::class_<::linalg::vec<float, 3>>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const float &, const float &, const float &>(), nb::arg("x_"), nb::arg("y_"), nb::arg("z_"));
    cls.def(::nanobind::detail::reflect_init<const ::linalg::vec<float, 2> &, const float &>(), nb::arg("xy"), nb::arg("z_"));
    cls.def(::nanobind::detail::reflect_init<const float &>(), nb::arg("s"));
    cls.def(::nanobind::detail::reflect_init<const float *>(), nb::arg("p"));
    cls.def(::nanobind::detail::reflect_init<const ::linalg::vec<float, 3> &>());
    cls.def_rw("x", &::linalg::vec<float, 3>::x);
    cls.def_rw("y", &::linalg::vec<float, 3>::y);
    cls.def_rw("z", &::linalg::vec<float, 3>::z);
    cls.def("__getitem__", [](const ::linalg::vec<float, 3> &self, int a0) -> const float & { return self.operator[](::std::forward<int>(a0)); }, nb::is_operator());
    cls.def("__getitem__", [](::linalg::vec<float, 3> &self, int a0) -> float & { return self.operator[](::std::forward<int>(a0)); }, nb::is_operator());
    cls.def("xy", [](const ::linalg::vec<float, 3> &self) -> const ::linalg::vec<float, 2> & { return self.xy(); }, nb::rv_policy::reference_internal);
    cls.def("xy", [](::linalg::vec<float, 3> &self) -> ::linalg::vec<float, 2> & { return self.xy(); }, nb::rv_policy::reference_internal);
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

template <class Self>
static void nbgen_bind___linalg__vec_Lfloat_C2_R(nb::module_ &m) {
    if (nb::type<::linalg::vec<float, 2>>().is_valid()) return;
    const char *py_name = nb::hasattr(m, "vecFloat2") ? "linalg_vecFloat2" : "vecFloat2";
    auto cls = nb::class_<::linalg::vec<float, 2>>(m, py_name);
    cls.def(::nanobind::detail::reflect_init<>());
    cls.def(::nanobind::detail::reflect_init<const float &, const float &>(), nb::arg("x_"), nb::arg("y_"));
    cls.def(::nanobind::detail::reflect_init<const float &>(), nb::arg("s"));
    cls.def(::nanobind::detail::reflect_init<const float *>(), nb::arg("p"));
    cls.def(::nanobind::detail::reflect_init<const ::linalg::vec<float, 2> &>());
    cls.def_rw("x", &::linalg::vec<float, 2>::x);
    cls.def_rw("y", &::linalg::vec<float, 2>::y);
    cls.def("__getitem__", [](const ::linalg::vec<float, 2> &self, int a0) -> const float & { return self.operator[](::std::forward<int>(a0)); }, nb::is_operator());
    cls.def("__getitem__", [](::linalg::vec<float, 2> &self, int a0) -> float & { return self.operator[](::std::forward<int>(a0)); }, nb::is_operator());
    if constexpr (requires(::std::ostream &os, const Self &t) { os << t; })
        cls.def("__str__", [](const Self &self) { ::std::ostringstream oss; oss << self; return oss.str(); });
}

} // namespace nbgen

NB_MODULE(linalg_ext, m) {
    nbgen::nbgen_bind___linalg__vec_Lfloat_C3_R(m);
    nbgen::nbgen_bind___linalg__vec_Lfloat_C2_R(m);
    nbgen::nbgen_bind___linalg__vec_Lfloat_C3_R(m);
}
